site:
  name: "My Zuopins Site"
  bio: "A brief bio about the user."
links:
  - title: "Link 1"
    url: "https://example.com"
  - title: "Link 2"
    url: "https://example.com"
  - title: "Link 3"
    url: "https://example.com"
